const review = [
    {id:1, name:'Talha Tanu', img:'https://image.freepik.com/free-photo/cheerful-curly-business-girl-wearing-glasses_176420-206.jpg',work:'Student', review:'This Shop Dresses Too good.', rating:4},
    {id:2, name:'Sinjhi Sanha', img:'https://image.freepik.com/free-photo/cheerful-curly-business-girl-wearing-glasses_176420-206.jpg',work:'Job', review:'This Shop Dresses is best.', rating:5},
    {id:3, name:'Sarker Ahmed', img:'https://image.freepik.com/free-photo/cheerful-curly-business-girl-wearing-glasses_176420-206.jpg',work:'Engineer', review:'This Shop Dresses is very good.', rating:5},
]